// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNotificationFilter(arg1) {
  return window['go']['app']['App']['AddNotificationFilter'](arg1);
}

export function AddRecentFile(arg1, arg2) {
  return window['go']['app']['App']['AddRecentFile'](arg1, arg2);
}

export function AddRecentProject(arg1) {
  return window['go']['app']['App']['AddRecentProject'](arg1);
}

export function BackupSettings() {
  return window['go']['app']['App']['BackupSettings']();
}

export function BackupSettingsAPI() {
  return window['go']['app']['App']['BackupSettingsAPI']();
}

export function CancelGeneration(arg1) {
  return window['go']['app']['App']['CancelGeneration'](arg1);
}

export function CancelScheduledUpdate() {
  return window['go']['app']['App']['CancelScheduledUpdate']();
}

export function CancelUpdateDownload() {
  return window['go']['app']['App']['CancelUpdateDownload']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ClearActivityLogs(arg1, arg2) {
  return window['go']['app']['App']['ClearActivityLogs'](arg1, arg2);
}

export function ClearMetrics(arg1, arg2) {
  return window['go']['app']['App']['ClearMetrics'](arg1, arg2);
}

export function ClearNotificationHistory() {
  return window['go']['app']['App']['ClearNotificationHistory']();
}

export function ClearNotificationQueue() {
  return window['go']['app']['App']['ClearNotificationQueue']();
}

export function ClearRecentFiles() {
  return window['go']['app']['App']['ClearRecentFiles']();
}

export function ClearRecentProjects() {
  return window['go']['app']['App']['ClearRecentProjects']();
}

export function ClearValidationCache() {
  return window['go']['app']['App']['ClearValidationCache']();
}

export function CreateErrorReport(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['CreateErrorReport'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['app']['App']['DeleteBackup'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DetectFileFormat(arg1, arg2) {
  return window['go']['app']['App']['DetectFileFormat'](arg1, arg2);
}

export function DisableDoNotDisturbMode() {
  return window['go']['app']['App']['DisableDoNotDisturbMode']();
}

export function DisablePlugin(arg1, arg2) {
  return window['go']['app']['App']['DisablePlugin'](arg1, arg2);
}

export function DismissAllToasts() {
  return window['go']['app']['App']['DismissAllToasts']();
}

export function DismissToast(arg1) {
  return window['go']['app']['App']['DismissToast'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['app']['App']['DownloadUpdate'](arg1);
}

export function EnableDoNotDisturbMode(arg1) {
  return window['go']['app']['App']['EnableDoNotDisturbMode'](arg1);
}

export function EnablePlugin(arg1, arg2) {
  return window['go']['app']['App']['EnablePlugin'](arg1, arg2);
}

export function ExecuteNotificationAction(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteNotificationAction'](arg1, arg2, arg3);
}

export function ExportActivityLogs(arg1, arg2) {
  return window['go']['app']['App']['ExportActivityLogs'](arg1, arg2);
}

export function ExportGeneratedServer(arg1, arg2) {
  return window['go']['app']['App']['ExportGeneratedServer'](arg1, arg2);
}

export function ExportNotificationHistory(arg1, arg2) {
  return window['go']['app']['App']['ExportNotificationHistory'](arg1, arg2);
}

export function ExportProject(arg1) {
  return window['go']['app']['App']['ExportProject'](arg1);
}

export function ExportSettings() {
  return window['go']['app']['App']['ExportSettings']();
}

export function ExportValidationResult(arg1) {
  return window['go']['app']['App']['ExportValidationResult'](arg1);
}

export function FileExists(arg1) {
  return window['go']['app']['App']['FileExists'](arg1);
}

export function ForceGarbageCollection() {
  return window['go']['app']['App']['ForceGarbageCollection']();
}

export function GenerateServer(arg1) {
  return window['go']['app']['App']['GenerateServer'](arg1);
}

export function GetActiveToasts() {
  return window['go']['app']['App']['GetActiveToasts']();
}

export function GetActivityLogs(arg1, arg2) {
  return window['go']['app']['App']['GetActivityLogs'](arg1, arg2);
}

export function GetAggregatedMetrics(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetAggregatedMetrics'](arg1, arg2, arg3);
}

export function GetApplicationStatus(arg1) {
  return window['go']['app']['App']['GetApplicationStatus'](arg1);
}

export function GetAvailableBackups() {
  return window['go']['app']['App']['GetAvailableBackups']();
}

export function GetDefaultOpenAPIFilters() {
  return window['go']['app']['App']['GetDefaultOpenAPIFilters']();
}

export function GetErrorReports(arg1, arg2) {
  return window['go']['app']['App']['GetErrorReports'](arg1, arg2);
}

export function GetGenerationHistory(arg1) {
  return window['go']['app']['App']['GetGenerationHistory'](arg1);
}

export function GetGenerationJob(arg1) {
  return window['go']['app']['App']['GetGenerationJob'](arg1);
}

export function GetLastUpdateCheck() {
  return window['go']['app']['App']['GetLastUpdateCheck']();
}

export function GetMemoryUsage() {
  return window['go']['app']['App']['GetMemoryUsage']();
}

export function GetNotificationConfig() {
  return window['go']['app']['App']['GetNotificationConfig']();
}

export function GetNotificationHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetNotificationHistory'](arg1, arg2, arg3);
}

export function GetNotificationQueue() {
  return window['go']['app']['App']['GetNotificationQueue']();
}

export function GetNotificationStats() {
  return window['go']['app']['App']['GetNotificationStats']();
}

export function GetPerformanceAlerts(arg1, arg2) {
  return window['go']['app']['App']['GetPerformanceAlerts'](arg1, arg2);
}

export function GetPerformanceMetrics() {
  return window['go']['app']['App']['GetPerformanceMetrics']();
}

export function GetPerformanceThresholds(arg1) {
  return window['go']['app']['App']['GetPerformanceThresholds'](arg1);
}

export function GetPlugin(arg1, arg2) {
  return window['go']['app']['App']['GetPlugin'](arg1, arg2);
}

export function GetPluginCapabilities(arg1) {
  return window['go']['app']['App']['GetPluginCapabilities'](arg1);
}

export function GetPluginPermissions(arg1) {
  return window['go']['app']['App']['GetPluginPermissions'](arg1);
}

export function GetPlugins(arg1) {
  return window['go']['app']['App']['GetPlugins'](arg1);
}

export function GetPluginsByCapability(arg1, arg2) {
  return window['go']['app']['App']['GetPluginsByCapability'](arg1, arg2);
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['app']['App']['GetProjects']();
}

export function GetRecentFiles() {
  return window['go']['app']['App']['GetRecentFiles']();
}

export function GetRecentProjects() {
  return window['go']['app']['App']['GetRecentProjects']();
}

export function GetRollbackCapabilities() {
  return window['go']['app']['App']['GetRollbackCapabilities']();
}

export function GetScheduledJob() {
  return window['go']['app']['App']['GetScheduledJob']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSettingsBackupPath() {
  return window['go']['app']['App']['GetSettingsBackupPath']();
}

export function GetSettingsFilePath() {
  return window['go']['app']['App']['GetSettingsFilePath']();
}

export function GetSupportedFileFormats() {
  return window['go']['app']['App']['GetSupportedFileFormats']();
}

export function GetSystemMetrics(arg1) {
  return window['go']['app']['App']['GetSystemMetrics'](arg1);
}

export function GetTemplateMetrics(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTemplateMetrics'](arg1, arg2, arg3);
}

export function GetUpdateAnalytics() {
  return window['go']['app']['App']['GetUpdateAnalytics']();
}

export function GetUpdateConfiguration() {
  return window['go']['app']['App']['GetUpdateConfiguration']();
}

export function GetUpdateHistory() {
  return window['go']['app']['App']['GetUpdateHistory']();
}

export function GetUpdateSettings() {
  return window['go']['app']['App']['GetUpdateSettings']();
}

export function GetUpdateStatus() {
  return window['go']['app']['App']['GetUpdateStatus']();
}

export function GetValidationCacheStats() {
  return window['go']['app']['App']['GetValidationCacheStats']();
}

export function HasSettingsBackup() {
  return window['go']['app']['App']['HasSettingsBackup']();
}

export function ImportOpenAPISpec(arg1) {
  return window['go']['app']['App']['ImportOpenAPISpec'](arg1);
}

export function ImportOpenAPISpecFromURL(arg1) {
  return window['go']['app']['App']['ImportOpenAPISpecFromURL'](arg1);
}

export function ImportProject(arg1) {
  return window['go']['app']['App']['ImportProject'](arg1);
}

export function ImportSettings() {
  return window['go']['app']['App']['ImportSettings']();
}

export function InstallPlugin(arg1, arg2) {
  return window['go']['app']['App']['InstallPlugin'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['app']['App']['InstallUpdate']();
}

export function LoadPlugin(arg1, arg2) {
  return window['go']['app']['App']['LoadPlugin'](arg1, arg2);
}

export function LogActivity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['LogActivity'](arg1, arg2, arg3, arg4, arg5);
}

export function MarkNotificationAsRead(arg1) {
  return window['go']['app']['App']['MarkNotificationAsRead'](arg1);
}

export function MigrateAndLoadSettings() {
  return window['go']['app']['App']['MigrateAndLoadSettings']();
}

export function OnShutdown(arg1) {
  return window['go']['app']['App']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['app']['App']['OnStartup'](arg1);
}

export function PauseNotifications() {
  return window['go']['app']['App']['PauseNotifications']();
}

export function PauseScheduledUpdate() {
  return window['go']['app']['App']['PauseScheduledUpdate']();
}

export function PauseUpdateDownload() {
  return window['go']['app']['App']['PauseUpdateDownload']();
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function RemoveNotificationFilter(arg1) {
  return window['go']['app']['App']['RemoveNotificationFilter'](arg1);
}

export function RemoveRecentFile(arg1) {
  return window['go']['app']['App']['RemoveRecentFile'](arg1);
}

export function ReportError(arg1) {
  return window['go']['app']['App']['ReportError'](arg1);
}

export function ResetSettings() {
  return window['go']['app']['App']['ResetSettings']();
}

export function ResolveAlert(arg1, arg2) {
  return window['go']['app']['App']['ResolveAlert'](arg1, arg2);
}

export function RestoreSettingsFromBackup() {
  return window['go']['app']['App']['RestoreSettingsFromBackup']();
}

export function RestoreSettingsFromBackupAPI() {
  return window['go']['app']['App']['RestoreSettingsFromBackupAPI']();
}

export function ResumeNotifications() {
  return window['go']['app']['App']['ResumeNotifications']();
}

export function ResumeScheduledUpdate() {
  return window['go']['app']['App']['ResumeScheduledUpdate']();
}

export function ResumeUpdateDownload() {
  return window['go']['app']['App']['ResumeUpdateDownload']();
}

export function RollbackToVersion(arg1) {
  return window['go']['app']['App']['RollbackToVersion'](arg1);
}

export function RollbackUpdate() {
  return window['go']['app']['App']['RollbackUpdate']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveFile'](arg1, arg2, arg3);
}

export function ScheduleUpdate(arg1, arg2) {
  return window['go']['app']['App']['ScheduleUpdate'](arg1, arg2);
}

export function ScheduleUpdateCheck(arg1) {
  return window['go']['app']['App']['ScheduleUpdateCheck'](arg1);
}

export function SearchActivityLogs(arg1, arg2) {
  return window['go']['app']['App']['SearchActivityLogs'](arg1, arg2);
}

export function SearchPlugins(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SearchPlugins'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchProjects(arg1) {
  return window['go']['app']['App']['SearchProjects'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['app']['App']['SelectFile'](arg1);
}

export function SetPerformanceThresholds(arg1, arg2) {
  return window['go']['app']['App']['SetPerformanceThresholds'](arg1, arg2);
}

export function ShowErrorToast(arg1, arg2) {
  return window['go']['app']['App']['ShowErrorToast'](arg1, arg2);
}

export function ShowInfoToast(arg1, arg2) {
  return window['go']['app']['App']['ShowInfoToast'](arg1, arg2);
}

export function ShowSuccessToast(arg1, arg2) {
  return window['go']['app']['App']['ShowSuccessToast'](arg1, arg2);
}

export function ShowSystemNotification(arg1) {
  return window['go']['app']['App']['ShowSystemNotification'](arg1);
}

export function ShowToastNotification(arg1) {
  return window['go']['app']['App']['ShowToastNotification'](arg1);
}

export function ShowWarningToast(arg1, arg2) {
  return window['go']['app']['App']['ShowWarningToast'](arg1, arg2);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['app']['App']['SkipUpdateVersion'](arg1);
}

export function StartPerformanceMonitoring(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartPerformanceMonitoring'](arg1, arg2, arg3);
}

export function TestNotificationFilter(arg1, arg2) {
  return window['go']['app']['App']['TestNotificationFilter'](arg1, arg2);
}

export function TestUpdateConnection() {
  return window['go']['app']['App']['TestUpdateConnection']();
}

export function UnloadPlugin(arg1, arg2) {
  return window['go']['app']['App']['UnloadPlugin'](arg1, arg2);
}

export function UpdateAppearanceSettings(arg1) {
  return window['go']['app']['App']['UpdateAppearanceSettings'](arg1);
}

export function UpdateEditorSettings(arg1) {
  return window['go']['app']['App']['UpdateEditorSettings'](arg1);
}

export function UpdateGenerationSettings(arg1) {
  return window['go']['app']['App']['UpdateGenerationSettings'](arg1);
}

export function UpdateLanguage(arg1) {
  return window['go']['app']['App']['UpdateLanguage'](arg1);
}

export function UpdateLogConfig(arg1, arg2) {
  return window['go']['app']['App']['UpdateLogConfig'](arg1, arg2);
}

export function UpdateNotificationConfig(arg1) {
  return window['go']['app']['App']['UpdateNotificationConfig'](arg1);
}

export function UpdateNotificationFilter(arg1) {
  return window['go']['app']['App']['UpdateNotificationFilter'](arg1);
}

export function UpdateNotificationSettings(arg1) {
  return window['go']['app']['App']['UpdateNotificationSettings'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['app']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateScheduledUpdate(arg1) {
  return window['go']['app']['App']['UpdateScheduledUpdate'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UpdateTheme(arg1) {
  return window['go']['app']['App']['UpdateTheme'](arg1);
}

export function UpdateUpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateUpdateSettings'](arg1);
}

export function UpdateWindowSettings(arg1) {
  return window['go']['app']['App']['UpdateWindowSettings'](arg1);
}

export function ValidateBackup(arg1) {
  return window['go']['app']['App']['ValidateBackup'](arg1);
}

export function ValidateSpec(arg1) {
  return window['go']['app']['App']['ValidateSpec'](arg1);
}

export function ValidateURL(arg1) {
  return window['go']['app']['App']['ValidateURL'](arg1);
}

export function ValidateUpdateConfiguration(arg1) {
  return window['go']['app']['App']['ValidateUpdateConfiguration'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2);
}
