// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['app']['App']['AddRecentProject'](arg1);
}

export function CancelGeneration(arg1) {
  return window['go']['app']['App']['CancelGeneration'](arg1);
}

export function ClearRecentProjects() {
  return window['go']['app']['App']['ClearRecentProjects']();
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function ExportSettings() {
  return window['go']['app']['App']['ExportSettings']();
}

export function FileExists(arg1) {
  return window['go']['app']['App']['FileExists'](arg1);
}

export function GenerateServer(arg1) {
  return window['go']['app']['App']['GenerateServer'](arg1);
}

export function GetDefaultOpenAPIFilters() {
  return window['go']['app']['App']['GetDefaultOpenAPIFilters']();
}

export function GetGenerationHistory(arg1) {
  return window['go']['app']['App']['GetGenerationHistory'](arg1);
}

export function GetGenerationJob(arg1) {
  return window['go']['app']['App']['GetGenerationJob'](arg1);
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['app']['App']['GetProjects']();
}

export function GetRecentProjects() {
  return window['go']['app']['App']['GetRecentProjects']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSettingsFilePath() {
  return window['go']['app']['App']['GetSettingsFilePath']();
}

export function ImportSettings() {
  return window['go']['app']['App']['ImportSettings']();
}

export function OnShutdown(arg1) {
  return window['go']['app']['App']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['app']['App']['OnStartup'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function ResetSettings() {
  return window['go']['app']['App']['ResetSettings']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['app']['App']['SelectFile'](arg1);
}

export function UpdateLanguage(arg1) {
  return window['go']['app']['App']['UpdateLanguage'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['app']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UpdateTheme(arg1) {
  return window['go']['app']['App']['UpdateTheme'](arg1);
}

export function UpdateWindowSettings(arg1) {
  return window['go']['app']['App']['UpdateWindowSettings'](arg1);
}

export function ValidateSpec(arg1) {
  return window['go']['app']['App']['ValidateSpec'](arg1);
}

export function ValidateURL(arg1) {
  return window['go']['app']['App']['ValidateURL'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2);
}
