// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function AddRecentProject(arg1:string):Promise<void>;

export function CancelGeneration(arg1:string):Promise<void>;

export function ClearRecentProjects():Promise<void>;

export function CreateProject(arg1:app.CreateProjectRequest):Promise<app.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function ExportProject(arg1:string):Promise<string>;

export function ExportSettings():Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GenerateServer(arg1:string):Promise<app.GenerationJob>;

export function GetDefaultOpenAPIFilters():Promise<Array<app.FileFilter>>;

export function GetGenerationHistory(arg1:string):Promise<Array<app.GenerationJob>>;

export function GetGenerationJob(arg1:string):Promise<app.GenerationJob>;

export function GetProject(arg1:string):Promise<app.Project>;

export function GetProjects():Promise<Array<app.Project>>;

export function GetRecentProjects():Promise<Array<app.Project>>;

export function GetSettings():Promise<app.AppSettings>;

export function GetSettingsFilePath():Promise<string>;

export function ImportProject(arg1:string):Promise<app.Project>;

export function ImportSettings():Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ResetSettings():Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:Array<app.FileFilter>):Promise<string>;

export function SearchProjects(arg1:string):Promise<Array<app.Project>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:Array<app.FileFilter>):Promise<string>;

export function UpdateLanguage(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:app.ProjectUpdateRequest):Promise<app.Project>;

export function UpdateSettings(arg1:app.AppSettings):Promise<void>;

export function UpdateTheme(arg1:string):Promise<void>;

export function UpdateWindowSettings(arg1:app.WindowSettings):Promise<void>;

export function ValidateSpec(arg1:string):Promise<app.ValidationResult>;

export function ValidateURL(arg1:string):Promise<app.ValidationResult>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
