name: Build and Release

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: false
        default: ''
      platforms:
        description: 'Platforms to build (all, windows, macos, linux)'
        required: false
        default: 'all'

env:
  GO_VERSION: '1.23'
  NODE_VERSION: '20'
  WAILS_VERSION: 'v2.10.1'

jobs:
  # Job to determine build matrix
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      should_release: ${{ steps.version.outputs.should_release }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION=${VERSION#v}  # Remove 'v' prefix
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            VERSION="0.0.0-dev.$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Determine build matrix
        id: matrix
        run: |
          PLATFORMS="${{ github.event.inputs.platforms || 'all' }}"
          
          if [[ "$PLATFORMS" == "all" ]]; then
            MATRIX='["windows-latest", "macos-latest", "ubuntu-latest"]'
          elif [[ "$PLATFORMS" == "windows" ]]; then
            MATRIX='["windows-latest"]'
          elif [[ "$PLATFORMS" == "macos" ]]; then
            MATRIX='["macos-latest"]'
          elif [[ "$PLATFORMS" == "linux" ]]; then
            MATRIX='["ubuntu-latest"]'
          else
            MATRIX='["windows-latest", "macos-latest", "ubuntu-latest"]'
          fi
          
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  # Main build job
  build:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.prepare.outputs.matrix) }}
        include:
          - os: windows-latest
            platform: windows
            arch: amd64
            extension: .exe
            artifact_name: MCPWeaver-windows-amd64
          - os: macos-latest
            platform: darwin
            arch: universal
            extension: .app
            artifact_name: MCPWeaver-macos-universal
          - os: ubuntu-latest
            platform: linux
            arch: amd64
            extension: ""
            artifact_name: MCPWeaver-linux-amd64

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@${{ env.WAILS_VERSION }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Build application
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          BUILD_DATE: ${{ github.event.head_commit.timestamp }}
          BUILD_COMMIT: ${{ github.sha }}
        run: |
          echo "Building Go backend for validation..."
          go build -v ./...
          echo "Backend build completed successfully"
          
          echo "Note: Full Wails build skipped for now to focus on validation"
          echo "Platform: ${{ matrix.platform }}/${{ matrix.arch }}"
          echo "Version: ${VERSION}"

      - name: Code signing (macOS)
        if: matrix.os == 'macos-latest' && github.event_name != 'pull_request'
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
        run: |
          if [[ -n "$MACOS_CERTIFICATE" ]]; then
            echo "Setting up code signing..."
            echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
            security create-keychain -p "$MACOS_KEYCHAIN_PWD" build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p "$MACOS_KEYCHAIN_PWD" build.keychain
            security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_KEYCHAIN_PWD" build.keychain
            
            # Sign the application
            /usr/bin/codesign --force -s "Developer ID Application" --options runtime "build/bin/${{ matrix.artifact_name }}.app" -v
          else
            echo "Skipping code signing - certificates not available"
          fi

      - name: Notarization (macOS)
        if: matrix.os == 'macos-latest' && github.event_name != 'pull_request'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          if [[ -n "$APPLE_ID" && -n "$APPLE_PASSWORD" ]]; then
            echo "Setting up notarization..."
            echo $APPLE_PASSWORD | xcrun altool --store-password-in-keychain-item "AC_PASSWORD" -u "$APPLE_ID" -p -
            
            # Create zip for notarization
            ditto -c -k --keepParent "build/bin/${{ matrix.artifact_name }}.app" "build/bin/${{ matrix.artifact_name }}.zip"
            
            # Submit for notarization
            xcrun altool --notarize-app \
              --primary-bundle-id "com.mcpweaver.app" \
              --username "$APPLE_ID" \
              --password "@keychain:AC_PASSWORD" \
              --file "build/bin/${{ matrix.artifact_name }}.zip"
            
            echo "Notarization submitted. Note: This is async and may take time to complete."
          else
            echo "Skipping notarization - credentials not available"
          fi

      - name: Code signing (Windows)
        if: matrix.os == 'windows-latest' && github.event_name != 'pull_request'
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
          WINDOWS_CERTIFICATE_PWD: ${{ secrets.WINDOWS_CERTIFICATE_PWD }}
        run: |
          if ($env:WINDOWS_CERTIFICATE) {
            Write-Output "Setting up code signing..."
            $certBytes = [Convert]::FromBase64String($env:WINDOWS_CERTIFICATE)
            [IO.File]::WriteAllBytes("certificate.pfx", $certBytes)
            
            # Sign the executable
            & 'C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe' sign /f certificate.pfx /p $env:WINDOWS_CERTIFICATE_PWD /tr http://timestamp.digicert.com /td sha256 /fd sha256 "build\bin\${{ matrix.artifact_name }}.exe"
          } else {
            Write-Output "Skipping code signing - certificate not available"
          }
        shell: powershell

      - name: Run tests
        run: |
          go test ./... -v -race -coverprofile=coverage.out
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: |
            coverage.out
            coverage.html

      - name: Create package
        run: |
          mkdir -p dist
          cd build/bin
          
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Create Windows installer (if NSIS available) or ZIP
            if command -v makensis >/dev/null 2>&1; then
              echo "Creating Windows installer..."
              # NSIS installer creation would go here
            fi
            # Create ZIP package
            7z a "../../dist/${{ matrix.artifact_name }}.zip" "${{ matrix.artifact_name }}.exe"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Create DMG (if available) or tar.gz
            if command -v create-dmg >/dev/null 2>&1; then
              echo "Creating DMG..."
              create-dmg \
                --volname "MCPWeaver" \
                --volicon "../../build/appicon.png" \
                --window-pos 200 120 \
                --window-size 600 300 \
                --icon-size 100 \
                --icon "${{ matrix.artifact_name }}.app" 175 120 \
                --hide-extension "${{ matrix.artifact_name }}.app" \
                --app-drop-link 425 120 \
                "../../dist/${{ matrix.artifact_name }}.dmg" \
                "${{ matrix.artifact_name }}.app"
            fi
            # Create tar.gz package
            tar -czf "../../dist/${{ matrix.artifact_name }}.tar.gz" "${{ matrix.artifact_name }}.app"
          else
            # Create AppImage (if available) or tar.gz
            # Create tar.gz package
            tar -czf "../../dist/${{ matrix.artifact_name }}.tar.gz" "${{ matrix.artifact_name }}"
          fi

      - name: Generate checksums
        run: |
          cd dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            certutil -hashfile "${{ matrix.artifact_name }}.zip" SHA256 > "${{ matrix.artifact_name }}.zip.sha256"
          else
            shasum -a 256 "${{ matrix.artifact_name }}"* > checksums.sha256
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            dist/*
          retention-days: 30

  # Release job (only on tags)
  release:
    needs: [prepare, build]
    if: needs.prepare.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find release-artifacts -name "*.zip" -o -name "*.tar.gz" -o -name "*.dmg" | while read file; do
            cp "$file" release-assets/
          done
          
          # Combine all checksums
          find release-artifacts -name "checksums.sha256" -exec cat {} \; > release-assets/checksums.sha256
          find release-artifacts -name "*.sha256" -exec cat {} \; >> release-assets/checksums.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: MCPWeaver ${{ needs.prepare.outputs.version }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: release-assets/*
          body: |
            ## MCPWeaver ${{ needs.prepare.outputs.version }}
            
            ### Changes
            - See commit history for detailed changes
            
            ### Downloads
            - **Windows**: `MCPWeaver-windows-amd64.zip`
            - **macOS**: `MCPWeaver-macos-universal.tar.gz` or `MCPWeaver-macos-universal.dmg`
            - **Linux**: `MCPWeaver-linux-amd64.tar.gz`
            
            ### Verification
            Use the `checksums.sha256` file to verify download integrity.
            
            ### Installation
            See the [documentation](README.md) for installation instructions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Cleanup job
  cleanup:
    needs: [build, release]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            
            const oldArtifacts = artifacts.data.artifacts.filter(artifact => {
              const ageInDays = (Date.now() - new Date(artifact.created_at)) / (1000 * 60 * 60 * 24);
              return ageInDays > 30;
            });
            
            for (const artifact of oldArtifacts) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }